x=int(input())
if(x==1):
    print("Janeiro")
elif(x==2):
    print("Fevereiro")
elif(x==3):
    print("Março")
elif(x==4):
    print("Abril")
elif(x==5):
    print("Maio")
elif(x==6):
    print("Junho")
elif(x==7):
    print("Julho")
elif(x==8):
    print("Agosto")
elif(x==9):
    print("Setembro")
elif(x==10):
    print("Outubro")
elif(x==11):
    print("Novembro")
elif(x==12):
    print("Dezembro")
else:
    print("Esta entrada não corresponde o desafio...")